### ISSUE TITLE
Instruction Based Autonomous

### ISSUE THREAD

**Issue by adamperlin** [redshiftrobotics/2856#10]
Currently, our autonomous has far too much boilerplate. We shouldn't need to call so many methods manually. Instead, we should switch to an instruction based autonomous, sample code to follow. This is purely an enhancement, but will be nice to have eventually, even if it's done in the off season. 

```java
import com.package.InstructionType
import com.package.InstructionEvaluator

public class Autonomous extends LinearOpmode {

    public double[][] instructions = { 
        {InstructionType.turn, 90.0, 2}, //turn 90 degrees, timeout 2
        {InstructionType.straight, 0.2, 2}, //move forward 0.2 rotations, timeout 2
        {InstructionType.MoveToLine, 0.0, 10} // move to line, 0 value is simply padding, 10 second timeout
    };

    @Override
    public void runOpMode() throws InterruptedException {
         DcMotor m1 = hardwareMap.dcMotor.get('m1');
         InstructionEvaluator e = new InstructionEvaluator(m1); //pass in motors so that they can be used internally
         e.eval(instructions);
    }
}

**Comment by mattkelsey** [comment]
Been working on this... Have a system that allows us to write shorthand for movement functions in `CustomSettingsActivity.java` directly in the UI of the Robot Controller application. This then also solves the issue of having to reupload code for just tweaking small values.

**Comment by adamperlin** [comment]
Will close because not relevant to 2017-18 season
