### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by zoecarver** [redshiftrobotics/2856#13]

**Comment by ariporad** [comment]
This should run a linter too.

**Comment by ariporad** [comment]
Possibly `prettier-java` + [KLint](https://ktlint.github.io/). Make sure to exclude FTC stuff.

**Comment by zoecarver** [comment]
KLint is great. prettier-java, however, is too unstable - I will keep looking for a good java linter but as is I think we are writing most of our code in kotlin anyway so I am not sure we need one.

**Comment by ariporad** [comment]
👍

**Comment by ariporad** [comment]
@zoecarver is this done?
